export const CREATE_CONVERSATION_REQUEST = "CREATE_CONVERSATION_REQUEST";
export const CREATE_CONVERSATION_SUCCESS = "CREATE_CONVERSATION_SUCCESS";
export const CREATE_CONVERSATION_FAIL = "CREATE_CONVERSATION_FAIL";

export const GET_CONVERSATIONS_REQUEST = "GET_CONVERSATIONS_REQUEST";
export const GET_CONVERSATIONS_SUCCESS = "GET_CONVERSATIONS_SUCCESS";
export const GET_CONVERSATIONS_FAIL = "GET_CONVERSATIONS_FAIL";

export const USER_CONVERSATIONS_REQUEST = "USER_CONVERSATIONS_REQUEST";
export const USER_CONVERSATIONS_SUCCESS = "USER_CONVERSATIONS_SUCCESS";
export const USER_CONVERSATIONS_FAIL = "USER_CONVERSATIONS_FAIL";

export const GET_USERS_CONVERSATIONS_REQUEST =
  "GET_USERS_CONVERSATIONS_REQUEST";
export const GET_USERS_CONVERSATIONS_SUCCESS =
  "GET_USERS_CONVERSATIONS_SUCCESS";
export const GET_USERS_CONVERSATIONS_FAIL = "GET_USERS_CONVERSATIONS_FAIL";
