export const CREATE_OFFER_REQUEST = "CREATE_OFFER_REQUEST";
export const CREATE_OFFER_SUCCESS = "CREATE_OFFER_SUCCESS";
export const CREATE_OFFER_FAIL = "CREATE_OFFER_FAIL";

export const GET_OFFERS_REQUEST = "GET_OFFERS_REQUEST";
export const GET_OFFERS_SUCCESS = "GET_OFFERS_SUCCESS";
export const GET_OFFERS_FAIL = "GET_OFFERS_FAIL";

export const MY_PRODUCT_OFFERS_REQUEST = "MY_PRODUCT_OFFERS_REQUEST";
export const MY_PRODUCT_OFFERS_SUCCESS = "MY_PRODUCT_OFFERS_SUCCESS";
export const MY_PRODUCT_OFFERS_FAIL = "MY_PRODUCT_OFFERS_FAIL";

export const OFFER_DETAILS_REQUEST = "OFFER_DETAILS_REQUEST";
export const OFFER_DETAILS_SUCCESS = "OFFER_DETAILS_SUCCESS";
export const OFFER_DETAILS_FAIL = "OFFER_DETAILS_FAIL";

export const MY_OFFERS_REQUEST = "MY_OFFERS_REQUEST";
export const MY_OFFERS_SUCCESS = "MY_OFFERS_SUCCESS";
export const MY_OFFERS_FAIL = "MY_OFFERS_FAIL";

export const DELETE_OFFER_REQUEST = "DELETE_OFFER_REQUEST";
export const DELETE_OFFER_SUCCESS = "DELETE_OFFER_SUCCESS";
export const DELETE_OFFER_FAIL = "DELETE_OFFER_FAIL";

export const TRACK_OFFER_REQUEST = "TRACK_OFFER_REQUEST";
export const TRACK_OFFER_SUCCESS = "TRACK_OFFER_SUCCESS";
export const TRACK_OFFER_FAIL = "TRACK_OFFER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
