export const USER_BYID_REQUEST = "USER_BYID_REQUEST";
export const USER_BYID_SUCCESS = "USER_BYID_SUCCESS";
export const USER_BYID_FAIL = "USER_BYID_FAIL";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
